sudo: required
language: elixir
services:
  - docker
elixir:
  - 1.8.2
otp_release:
  # - 19.2
  - 22.0.4
env:
  - MIX_ENV=test
before_script:
  - mix local.hex --force && mix deps.get
script:
  - mix test
  - mix format --check-formatted
  - echo skipping dialyzer check # mix dialyzer --halt-exit-status

# https://docs.travis-ci.com/user/docker/
after_success:
  - echo $TRAVIS_COMMIT
  - "docker build -t file_beam:$TRAVIS_COMMIT ."
  - docker tag file_beam:$TRAVIS_COMMIT nietaki/file_beam:$TRAVIS_COMMIT
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nietaki/file_beam:$TRAVIS_COMMIT
  - docker images
